# Omakase Ruby styling for Rails
inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'test/fixtures/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 150

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

# Ignore trailing whitespace and missing final newlines
Layout/TrailingWhitespace:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 3

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 3

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '()'
    '%i': '()'
    '%q': '()'
    '%Q': '()'
    '%r': '()'
    '%s': '()'
    '%w': '()'
    '%W': '()'
    '%x': '()'

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]`

Bundler/OrderedGems:
  Enabled: true